# Generated by Django 5.2.13 on 2026-06-11 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. '2026-06-11-B3'", max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_manual', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('partial', 'Partial'), ('cancelled', 'Cancelled')], default='running', max_length=16)),
                ('summary', models.JSONField(default=dict)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs_batchrun',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=2048)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('platforms', models.CharField(default='linkedin_pulse,notion,medium', max_length=256)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('partial', 'Partial'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('batch_label', models.CharField(blank=True, max_length=32)),
                ('blog_title', models.CharField(blank=True, max_length=512)),
                ('blog_content', models.TextField(blank=True)),
                ('blog_description', models.TextField(blank=True)),
                ('blog_seo_title', models.CharField(blank=True, max_length=512)),
                ('blog_seo_desc', models.CharField(blank=True, max_length=512)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=2048)),
                ('sheet_row', models.IntegerField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_jobs', to='jobs.batchrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs_blogjob',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=2048)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('platforms', models.CharField(default='x,facebook,linkedin', help_text='Comma-separated: x,facebook,linkedin', max_length=256)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('partial', 'Partial'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('batch_label', models.CharField(blank=True, max_length=32)),
                ('x_post', models.TextField(blank=True)),
                ('fb_post', models.TextField(blank=True)),
                ('li_post', models.TextField(blank=True)),
                ('sheet_row', models.IntegerField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posting_jobs', to='jobs.batchrun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs_postingjob',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('x', 'X (Twitter)'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('linkedin_pulse', 'LinkedIn Pulse'), ('medium', 'Medium'), ('notion', 'Notion'), ('devto', 'Dev.to'), ('wordpress', 'WordPress'), ('blogger', 'Blogger'), ('hackmd', 'HackMD'), ('linkmate', 'Linkmate'), ('google_sites', 'Google Sites'), ('paragraph', 'Paragraph'), ('calisthenics', 'Calisthenics'), ('substack', 'Substack')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('partial', 'Partial'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('post_url', models.URLField(blank=True, max_length=2048)),
                ('error_message', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('raw_output', models.TextField(blank=True)),
                ('blog_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='jobs.blogjob')),
            ],
            options={
                'db_table': 'jobs_blogresult',
                'unique_together': {('blog_job', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='PostingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('x', 'X (Twitter)'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('linkedin_pulse', 'LinkedIn Pulse'), ('medium', 'Medium'), ('notion', 'Notion'), ('devto', 'Dev.to'), ('wordpress', 'WordPress'), ('blogger', 'Blogger'), ('hackmd', 'HackMD'), ('linkmate', 'Linkmate'), ('google_sites', 'Google Sites'), ('paragraph', 'Paragraph'), ('calisthenics', 'Calisthenics'), ('substack', 'Substack')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed'), ('partial', 'Partial'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('post_url', models.URLField(blank=True, max_length=2048)),
                ('error_message', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('raw_output', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='jobs.postingjob')),
            ],
            options={
                'db_table': 'jobs_postingresult',
                'unique_together': {('job', 'platform')},
            },
        ),
    ]
