# Generated by Django 5.2.13 on 2026-06-11 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('x', 'X (Twitter)'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('linkedin_pulse', 'LinkedIn Pulse'), ('medium', 'Medium'), ('notion', 'Notion'), ('devto', 'Dev.to'), ('wordpress', 'WordPress'), ('blogger', 'Blogger'), ('hackmd', 'HackMD'), ('linkmate', 'Linkmate'), ('google_sites', 'Google Sites'), ('paragraph', 'Paragraph'), ('calisthenics', 'Calisthenics'), ('substack', 'Substack')], max_length=32)),
                ('login_email', models.CharField(blank=True, max_length=255)),
                ('login_password', models.CharField(blank=True, max_length=512)),
                ('handle', models.CharField(blank=True, max_length=128)),
                ('session_dir', models.CharField(blank=True, max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credentials_socialcredential',
                'ordering': ['platform'],
                'unique_together': {('user', 'platform')},
            },
        ),
    ]
