# Generated by Django 5.2.13 on 2026-06-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, choices=[('aniket', 'Aniket'), ('krishi', 'Krishi'), ('pranav', 'Pranav'), ('sameeksha', 'Sameeksha'), ('vansh', 'Vansh'), ('abhinav', 'Abhinav'), ('hritika', 'Hritika'), ('meenakshi', 'Meenakshi'), ('sanya', 'Sanya'), ('shivani', 'Shivani'), ('vijay', 'Vijay'), ('shrey', 'Shrey'), ('kamakshi', 'Kamakshi'), ('vishal', 'Vishal'), ('avdhesh', 'Avdhesh')], help_text="Matches '{Name} Social' and '{Name} Blog' tab prefix in Google Sheet", max_length=64, null=True, unique=True),
        ),
    ]
